# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# This line is irrelevant, just trying to force workflows to run. (Push event)

name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "55 */11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Fetch Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          SENTRY_DSN: ${{ vars.SENTRY_DSN }}
        run: yarn build

      - name: Upload Translation Strings
        env: # Or as an environment variable
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
          TRANSIFEX_TOKEN: "1/1d8c1f9e14b4c21d70dd3f6fccdd0ab16b691105"
        run: yarn transifex-push

      - name: Deploy 🚀
        if: github.event_name == 'push'
        uses: cloudflare/pages-action@v1
        with:
          accountId: 0445e37b88c2d301a0b3c411821b29c5
          projectName: tlg-guide
          directory: dist
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
